-- CreateEnum
CREATE TYPE "RealEstateAssetType" AS ENUM ('Agnostic', 'Mixed', 'Hospitality', 'Logistics_And_Industrial', 'Office', 'Residential', 'Senior_Living', 'Shopping_Center', 'Street_Retail', 'Student_Housing');

-- CreateEnum
CREATE TYPE "RealEstateInvestmentType" AS ENUM ('Lease_And_Operation', 'S_And_L', 'Core', 'Fix_And_Flip', 'Refurbishment', 'Value_Add', 'Opportunistic', 'Development');

-- CreateTable
CREATE TABLE "real_estate" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "asset" "RealEstateAssetType",
    "nRoomsLastYear" INTEGER,
    "noi" DOUBLE PRECISION,
    "occupancyLastYear" DOUBLE PRECISION,
    "walt" DOUBLE PRECISION,
    "nBeds" INTEGER,
    "investment" "RealEstateInvestmentType",
    "subRent" DOUBLE PRECISION,
    "rentPerSqm" DOUBLE PRECISION,
    "subYield" DOUBLE PRECISION,
    "capex" DOUBLE PRECISION,
    "capexPerSqm" DOUBLE PRECISION,
    "sale" DOUBLE PRECISION,
    "salePerSqm" DOUBLE PRECISION,
    "location" TEXT,
    "area" DOUBLE PRECISION,
    "value" DOUBLE PRECISION,
    "yield" DOUBLE PRECISION,
    "rent" DOUBLE PRECISION,
    "gcaAboveGround" DOUBLE PRECISION,
    "gcaBelowGround" DOUBLE PRECISION,
    "license" TEXT,
    "irr" DOUBLE PRECISION,
    "coc" DOUBLE PRECISION,
    "licenseStage" TEXT,
    "holdingPeriod" DOUBLE PRECISION,
    "breakEvenOccupancy" DOUBLE PRECISION,
    "vacancyRate" DOUBLE PRECISION,
    "estimatedRentValue" DOUBLE PRECISION,
    "occupancyRate" DOUBLE PRECISION,
    "moic" DOUBLE PRECISION,
    "price" DOUBLE PRECISION,
    "totalInvestment" DOUBLE PRECISION,
    "profitOnCost" DOUBLE PRECISION,
    "profit" DOUBLE PRECISION,
    "sofCosts" DOUBLE PRECISION,
    "sellPerSqm" DOUBLE PRECISION,
    "gdv" DOUBLE PRECISION,
    "wault" DOUBLE PRECISION,
    "debtServiceCoverageRatio" DOUBLE PRECISION,
    "expectedExitYield" DOUBLE PRECISION,
    "ltv" DOUBLE PRECISION,
    "ltc" DOUBLE PRECISION,
    "yieldOnCost" DOUBLE PRECISION,
    "images" TEXT[],
    "coInvestment" BOOLEAN,
    "gpEquityValue" DOUBLE PRECISION,
    "gpEquityPercentage" DOUBLE PRECISION,
    "totalEquityRequired" DOUBLE PRECISION,
    "sponsorPresentation" TEXT,
    "promoteStructure" TEXT,
    "projectIRR" DOUBLE PRECISION,
    "investorIRR" DOUBLE PRECISION,
    "coInvestmentHoldPeriod" DOUBLE PRECISION,
    "coInvestmentBreakEvenOccupancy" DOUBLE PRECISION,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "real_estate_pkey" PRIMARY KEY ("id")
);
